pages:
  stage: deploy
  image: busybox
  script: |
    mkdir .public
    sh build.sh
    cp -prfv build/* .public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
