pages:
  stage: deploy
  image: busybox
  script: |
    mkdir public .public
    echo '<meta http-equiv="refresh" content="0; URL=https://turkman.gitlab.io/devel/doc/wiki/" />' > public/index.html
    cp public/* .public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
